title: 基于qemu从0开始构建嵌入式linux系统
description: Quard Star tutorial with GitHub Pages.
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true